apiVersion: apps/v1
kind: Deployment
metadata:
  name: myfoods-deployment
  namespace: myfoods-ns
  labels:
    app: myfoods
spec:
  replicas: 3
  selector:
    matchLabels:
      app: myfoods
  template:
    metadata:
      labels:
        app: myfoods
    spec:
      containers:
      - name: myfoods
        image: myfoods:1.14.2
        ports:
        - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: myfoods-service
  namespace: myfoods-ns
spec:
  type: LoadBalancer
  selector:
    app: myfoods
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80